Repository 1024pix/renovate-config, pull requests merged in 2023-07, with the labels that each got.

#7 [TECH] :wrench: Configurer les labels et la planification de Renovate pour les configurations personnalisées
  README.md
  aggressive.json
  default.json
Labels: :rocket: Ready to Merge, tech-days-up

#12 Split non major dependencies upgrade
  default.json
  package.json
  presets/group-dependencies-non-major.json
Labels: :rocket: Ready to Merge, tech-days-up

#16 [FEATURE] Forcer une version mineur minimale de Node
  .nvmrc
  package.json
  presets/group-global-dependencies.json
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team, tech-days-up

#15 [BUGFIX] Le preset `confident` nécessite paiement à Renovate
  README.md
  auto-patch.json
  package.json
Labels: :rocket: Ready to Merge, Tech Review OK, cross-team, tech-days-up

#19 [TECH] :wrench: Rechercher les paquets exacts au lieu de tous ceux comprenant le nom de paquet
  presets/group-by-directory.json
  presets/group-global-dependencies.json
Labels: :rocket: Ready to Merge, tech-days-up

#25 [TECH] Nettoyage du preset de regroupement
  presets/group-global-dependencies.json
Labels: :rocket: Ready to Merge, Tech Review OK, enhancement, tech-days-up
